/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import src.ModelProduto;

public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
        carregaTabela();
        
        this.addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void keyPressed(KeyEvent e) {
                /*Atalho cadastrar*/
                if (e.getKeyCode() == KeyEvent.VK_ENTER){
                    ModelProduto prod = new ModelProduto(TextCod.getText(), TextNome.getText(), TextQuant.getText(), TextTipo.getText());
                    create(prod);
                    TextCod.setText("");
                    TextNome.setText("");
                    TextQuant.setText("");
                    TextTipo.setText("");  
                    carregaTabela();
                }
                /*Atalho editar*/
                else if (e.getKeyCode() == KeyEvent.VK_ENTER && e.isShiftDown()){
                    ModelProduto prod = new ModelProduto(TextCod.getText(), TextNome.getText(), TextQuant.getText(), TextTipo.getText());
                    editar(prod);
                    TextCod.setText("");
                    TextNome.setText("");
                    TextQuant.setText("");
                    TextTipo.setText("");  
                    carregaTabela();      
                }
                /*Atalho excluir*/
                else if (e.getKeyCode() == KeyEvent.VK_DELETE){
                    ModelProduto prod = new ModelProduto(TextCod.getText(), TextNome.getText(), TextQuant.getText(), TextTipo.getText());
                    excluir(prod);
                    TextCod.setText("");
                    TextNome.setText("");
                    TextQuant.setText("");
                    TextTipo.setText("");  
                    carregaTabela(); 
                }
                /*Atalho excluir tudo*/
                else if (e.getKeyCode() == KeyEvent.VK_DELETE && e.isShiftDown()){
                    excluirTudo();
                    carregaTabela();     
                }
            }

            @Override
            public void keyReleased(KeyEvent e) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
       
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("produtos?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        prodQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT p FROM Prod p");
        prodList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : prodQuery.getResultList();
        prodQuery1 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT p FROM Prod p");
        prodList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : prodQuery1.getResultList();
        prodQuery2 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT p FROM Prod p");
        prodList2 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : prodQuery2.getResultList();
        prodQuery3 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT p FROM Prod p");
        prodList3 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : prodQuery3.getResultList();
        prodQuery4 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT p FROM Prod p");
        prodList4 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : prodQuery4.getResultList();
        prodQuery5 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT p FROM Prod p");
        prodList5 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : prodQuery5.getResultList();
        prodQuery6 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT p FROM Prod p");
        prodList6 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : prodQuery6.getResultList();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TextCod = new javax.swing.JTextField();
        TextNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TextQuant = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TextTipo = new javax.swing.JTextField();
        BtnCad = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tb = new javax.swing.JTable();
        BtnExc = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        BtnExcT = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Cantarell", 0, 48)); // NOI18N
        jLabel1.setText("CADASTRO DE PRODUTOS");

        jLabel2.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        jLabel2.setText("Código:");

        TextCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextCodActionPerformed(evt);
            }
        });

        TextNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNomeActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        jLabel3.setText("Nome:");

        jLabel4.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        jLabel4.setText("Quant:");

        TextQuant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextQuantActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        jLabel5.setText("Tipo:");

        TextTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextTipoActionPerformed(evt);
            }
        });

        BtnCad.setText("Cadastrar");
        BtnCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCadActionPerformed(evt);
            }
        });
        BtnCad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnCadKeyPressed(evt);
            }
        });

        Tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome", "Quant", "Tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tb);

        BtnExc.setText("Excluir ");
        BtnExc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExcActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        BtnExcT.setText("Excluir tudo");
        BtnExcT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExcTActionPerformed(evt);
            }
        });

        jLabel6.setText("De double clique para selecionar um item cadastrado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextCod, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextQuant, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(65, 65, 65)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TextNome)
                                    .addComponent(TextTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(BtnCad, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtnExc, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtnExcT, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 743, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TextCod, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(TextNome, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(TextQuant, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(TextTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCad, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnExc, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnExcT, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextCodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextCodActionPerformed

    private void TextNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNomeActionPerformed

    private void TextQuantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextQuantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextQuantActionPerformed

    private void TextTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextTipoActionPerformed
    //Ações do botão cadastrar
    private void BtnCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCadActionPerformed
        ModelProduto prod = new ModelProduto(TextCod.getText(), TextNome.getText(), TextQuant.getText(), TextTipo.getText());
        create(prod);
        TextCod.setText("");
        TextNome.setText("");
        TextQuant.setText("");
        TextTipo.setText("");  
        carregaTabela();
    }//GEN-LAST:event_BtnCadActionPerformed
    
//Botão excluir
    private void BtnExcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExcActionPerformed
        ModelProduto prod = new ModelProduto(TextCod.getText());
        excluir(prod);
        TextCod.setText("");
        TextNome.setText("");
        TextQuant.setText("");
        TextTipo.setText("");  
        carregaTabela(); 
    }//GEN-LAST:event_BtnExcActionPerformed
//Botão editar
    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        ModelProduto prod = new ModelProduto(TextCod.getText(), TextNome.getText(), TextQuant.getText(), TextTipo.getText());
        editar(prod);
        TextCod.setText("");
        TextNome.setText("");
        TextQuant.setText("");
        TextTipo.setText("");  
        carregaTabela();        
    }//GEN-LAST:event_btnEditarActionPerformed
    
//Evento de clique na tabela
    private void TbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbMouseClicked
       if (evt.getClickCount() == 2){       
       int position = Tb.getSelectedRow();
       TextCod.setText(String.valueOf(Tb.getValueAt(position, 0)));
       TextNome.setText(String.valueOf(Tb.getValueAt(position, 1)));
       TextQuant.setText(String.valueOf(Tb.getValueAt(position,2)));
       TextTipo.setText(String.valueOf(Tb.getValueAt(position, 3)));
       }
    }//GEN-LAST:event_TbMouseClicked

    private void BtnExcTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExcTActionPerformed
        excluirTudo();
        carregaTabela();        
    }//GEN-LAST:event_BtnExcTActionPerformed

    private void BtnCadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnCadKeyPressed
        
    }//GEN-LAST:event_BtnCadKeyPressed

    
    private Connection con = null;
    //Metodo para criar uma linha
    public boolean create  (ModelProduto prod){
       con = Conection.getConnection();
       String sql = "INSERT INTO prod (cod, nome, quant, tipo) VALUES (?,?,?,?)"; 
       PreparedStatement stmt = null;
       
        try {
            stmt = con.prepareStatement(sql);
            stmt.setString(1, prod.getCod());
            stmt.setString(2, prod.getNome());
            stmt.setString(3, prod.getQuant());
            stmt.setString(4, prod.getTipo());
            stmt.executeUpdate();
            return true;
        } catch (SQLException ex) {
            System.err.println("erro" + ex);
            return false;
        }finally{
            Conection.closeConnection(con, stmt);
        }
    } 
    //Método para editar tabela
    public boolean editar(ModelProduto prod){
       con = Conection.getConnection();
       String sql = "UPDATE prod SET nome='" + prod.getNome() + "', quant='" + prod.getQuant() + "', tipo='" + prod.getTipo() + "' WHERE cod=" + prod.getCod() + ""; 
       PreparedStatement stmt = null;
       
        try {
            stmt = con.prepareStatement(sql);
            
            stmt.executeUpdate();
            return true;
        } catch (SQLException ex) {
            System.err.println("erro" + ex);
            return false;
        }finally{
            Conection.closeConnection(con, stmt);
        }
        
    }
    public boolean excluir(ModelProduto prod){
       con = Conection.getConnection();
       String sql = "DELETE FROM prod WHERE cod="+prod.getCod();
       PreparedStatement stmt = null;
       
        try {
            stmt = con.prepareStatement(sql);
            
            stmt.executeUpdate();
            return true;
        } catch (SQLException ex) {
            System.err.println("erro" + ex);
            return false;
        }finally{
            Conection.closeConnection(con, stmt);
        }
    }
    public boolean excluirTudo(){
       con = Conection.getConnection();
       String sql = "TRUNCATE TABLE prod";
       PreparedStatement stmt = null;
       
        try {
            stmt = con.prepareStatement(sql);
            
            stmt.executeUpdate();
            return true;
        } catch (SQLException ex) {
            System.err.println("erro" + ex);
            return false;
        }finally{
            Conection.closeConnection(con, stmt);
        }
    }
    //Método para carregar os dados do banco de dados
    public void carregaTabela(){
        DefaultTableModel modelo = (DefaultTableModel) Tb.getModel();
        modelo.setNumRows(0);
        
        try{
            con = Conection.getConnection();
            PreparedStatement pstm;
            ResultSet rs;
            
            pstm = con.prepareStatement("select * from prod;");
            rs = pstm.executeQuery();
            
            while(rs.next()){
                modelo.addRow(new Object[]{
                    rs.getInt(1),
                    rs.getString(2),
                    rs.getInt(3),
                    rs.getString(4)
                });
            }            
            Conection.closeConnection(con, pstm, rs);
        }catch(Exception ErroSql){
            JOptionPane.showMessageDialog(null, "Erro"+ErroSql, "ERRO", JOptionPane.ERROR_MESSAGE);
        }
        
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCad;
    private javax.swing.JButton BtnExc;
    private javax.swing.JButton BtnExcT;
    private javax.swing.JTable Tb;
    private javax.swing.JTextField TextCod;
    private javax.swing.JTextField TextNome;
    private javax.swing.JTextField TextQuant;
    private javax.swing.JTextField TextTipo;
    private javax.swing.JButton btnEditar;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private java.util.List<src.Prod> prodList;
    private java.util.List<src.Prod> prodList1;
    private java.util.List<src.Prod> prodList2;
    private java.util.List<src.Prod> prodList3;
    private java.util.List<src.Prod> prodList4;
    private java.util.List<src.Prod> prodList5;
    private java.util.List<src.Prod> prodList6;
    private javax.persistence.Query prodQuery;
    private javax.persistence.Query prodQuery1;
    private javax.persistence.Query prodQuery2;
    private javax.persistence.Query prodQuery3;
    private javax.persistence.Query prodQuery4;
    private javax.persistence.Query prodQuery5;
    private javax.persistence.Query prodQuery6;
    // End of variables declaration//GEN-END:variables
}
